version: "3.8"

services:
  promtail:
    image: grafana/promtail:2.9.4
    entrypoint:
      - /bin/sh
      - -c
    volumes:
      - app-logs:/var/log/app
      - ./promtail/config.yml:/etc/promtail/config.yml
    environment:
      - LOKI_TOKEN=${LOKI_TOKEN}
    command:
      - |
        mkdir -p /run/promtail
        printf '%s' "$$LOKI_TOKEN" > /run/promtail/token
        exec /usr/bin/promtail -config.file=/etc/promtail/config.yml
    networks:
      - app-network
    depends_on:
      - app
