server:
  http_listen_port: 9080

positions:
  filename: /tmp/positions.yaml

client:
  url: https://loki.kang-sm.dev/loki/api/v1/push
  bearer_token_file: /run/promtail/token

scrape_configs:
  - job_name: renzzle-backend
    static_configs:
      - targets:
          - localhost
        labels:
          job: renzzle-backend
          __path__: /var/log/app/application.log
